### ISSUE TITLE
Release on npm for Hoobs users

### ISSUE THREAD

**Issue by lc808** [lukasroegner/homebridge-appletv#5]
Hello,

is it possible to release this plugin, so hoobs users could also use it?

thx

**Comment by lukasroegner** [comment]
Published on NPM with package name `@lukas.roegner/homebridge-appletv`

**Comment by apexad** [comment]
Why the scope?  How is that suppose to work with homebridge or hoops?

**Comment by lukasroegner** [comment]
NPM didn't let me use `homebridge-appletv` (too similar to other package names). As scoped packages are not supported by homebridge, I renamed the complete plugin and published it on NPM: `homebrige-apple-tv-remote`.
